# Generated by Django 6.0.7 on 2026-07-25 17:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="client_message_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Client-generated idempotency key — a retried send with the same key returns the original message instead of creating a duplicate.",
                max_length=64,
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_message_id", ""), _negated=True),
                fields=("conversation", "sender", "client_message_id"),
                name="unique_client_message_id_per_sender_conversation",
            ),
        ),
    ]
