# Generated by Django 6.0.7 on 2026-08-16 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_alter_sharedfile_file'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sharedfile',
            new_name='messaging_s_convers_9e7993_idx',
            old_name='messaging_s_convers_4b4836_idx',
        ),
    ]
