# Generated by Django 6.0.7 on 2026-07-22 11:25

import apps.meetings.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=200)),
                ("scheduled_start", models.DateTimeField()),
                ("scheduled_end", models.DateTimeField()),
                ("actual_start", models.DateTimeField(blank=True, null=True)),
                ("actual_end", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("live", "Live"),
                            ("ended", "Ended"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=10,
                    ),
                ),
                (
                    "room_slug",
                    models.SlugField(
                        default=apps.meetings.utils.generate_room_slug,
                        editable=False,
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("waiting_room_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["scheduled_start"],
            },
        ),
        migrations.CreateModel(
            name="MeetingInvite",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("accepted", "Accepted"), ("declined", "Declined")],
                        default="pending",
                        max_length=8,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MeetingParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("host", "Host"), ("participant", "Participant")],
                        default="participant",
                        max_length=11,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("waiting", "Waiting"), ("admitted", "Admitted"), ("denied", "Denied")],
                        default="admitted",
                        max_length=8,
                    ),
                ),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
