# Generated by Django 6.0.7 on 2026-07-22 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("meetings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="host",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hosted_meetings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="meetinginvite",
            name="invited_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meeting_invites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="meetinginvite",
            name="meeting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="invites", to="meetings.meeting"
            ),
        ),
        migrations.AddField(
            model_name="meetingparticipant",
            name="meeting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="meetings.meeting",
            ),
        ),
        migrations.AddField(
            model_name="meetingparticipant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meeting_participations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(fields=["host", "status"], name="meetings_me_host_id_939657_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="meetinginvite",
            unique_together={("meeting", "invited_user")},
        ),
        migrations.AlterUniqueTogether(
            name="meetingparticipant",
            unique_together={("meeting", "user")},
        ),
    ]
